name: Integracao IBM Cloud

on:
  push:
    branches: [ main, master ]

jobs:
  banco-digital-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: npm install @ibm-cloud/cloudant ibm-cloud-sdk-core

      - name: GLOBAL - Conexao Gateway SWIFT
        run: node swift-gateway.js
        env:
          CLOUDANT_API_KEY: ${{ secrets.CLOUDANT_API_KEY }}
          CLOUDANT_URL: ${{ secrets.CLOUDANT_URL }}
